### ISSUE TITLE
[Suggestion] Allow starting health to be set below minimum health

### ISSUE THREAD

**Issue by Luke616** [Terrails/StatsKeeper#17]
Hello,

Something I would love is to have the starting health be below the minimum health for factoring in health loss on death. An example of how this could be used in pack dev would be to have the player start with 5 hearts (starting health = 10), and have a maximum health of 20 hearts (max health = 40). However, on death one heart past the vanilla 10 hearts (min health = 20) would be lost (health lost on death = 2), but those first 5 extra hearts would never be removed once gained. This allows for a more finely-tuned system which punishes the player for dying, but only up to a certain point.

Thanks for considering this feature request,
- Luke

**Comment by Terrails** [comment]
So basically custom starting health. I'll probably remove the start with min health option and then just add an option with which you can set it to whatever you want (custom, max or min)

**Comment by Terrails** [comment]
Just to get more info about the suggestion. You want a custom starting health, I get that. But you want it to work below MIN_HEALTH with removal... etc (like normal), but when the player manages to get to MIN_HEALTH with the items, the health will not be removed until the player goes over MIN_HEALTH.

**Comment by Luke616** [comment]
Yes! That's exactly the sort of thing I was imagining. A threshold above which health would be removed, but below which it would not be.

**Comment by Terrails** [comment]
I imagined it like this. If you are under the threshold, you'll lose health till min is reached. But when you reach the threshold your lowest health will be the threshold instead of min from now on. 
Or did you imagine it like this, while you are under the threshold you don't lose any health till you go over it.

**Comment by Luke616** [comment]
I imagined it the second way, almost like any health below the threshold would be permanent and any above the threshold would be "temporary" that you could possibly lose on death. The implementation you discussed in the edit sounds great!

**Comment by Luke616** [comment]
Awesome! Thank you so much again for granting this request and for making a fantastic mod which suits my needs as a pack developer perfectly!

**Comment by Terrails** [comment]
Okay, I just uploaded the file to curseforge. Make sure to test it because I'm pretty sure to it will have some bugs since I didn't test every scenario. 

Make sure to recreate your config file because I changed a lot of information in it. 
Basically you add your threshold amount with "KEEP" in the same line, so "10 KEEP", and that will be the threshold you wanted (above 10 health the player will lose health), if you want the thresholds which I thought about just put the number without anything, you can have as many of those as you want.
Make sure if using "KEEP" together with that to use "KEEP" only once and make it the smallest number. 
You also have a starting health option now, just make sure its inside min and max health and below the lowest threshold.

I'll explain this more clearly when I update the fabric version and have the time for the wiki page.

**Comment by Luke616** [comment]
It seems to be working great for the purposes I wanted - thank you so much for incorporating this feature!
