### ISSUE TITLE
When max_health and starting_health set to over 20, The player starts at 20 when a new world is started

### ISSUE THREAD

**Issue by adamf30** [Terrails/StatsKeeper#30]
I downloaded the Fabric version of StatsKeeper - and Made changes in the config file; however, when I start a new world, the health always starts at 20 as opposed to the max health that I set to.

How to reproduce:
1. Change "max_health" to a value higher than 20 and "starting_health" to MAX or a value higher than 20
2. Open Minecraft and start a new world
3. Health is started at 20 as opposed to a higher value.

**Comment by Terrails** [comment]
I can't reproduce this. The only thing that I think could be happening is that you set "starting_health" to a value that's higher than max health. "starting_health" has to be a value between min and max health.

**Comment by adamf30** [comment]
You can't? Well, here's the config file.

[config.zip](https://github.com/Terrails/StatsKeeper/files/5520784/config.zip)

**Comment by Terrails** [comment]
Still can't reproduce it. I copied your config file over to my game and it worked like it should. The only thing that I noticed is that the health is at 20 instead of being the max 220 on spawn, which is most definitely a bug. If that's what you meant, then I will shortly fix that. I thought that you meant that a player spawned with 20 health max even though it was set higher.

**Comment by Terrails** [comment]
I just uploaded the "fixed" version to curseforge, it should fix the bug I mentioned in the previous comment. It might've been the thing you've been experiencing.

**Comment by adamf30** [comment]
This solved the issue, thanks.
